
'use client';

import { useFormStatus } from 'react-dom';
import { useActionState, useEffect } from 'react';
import type { State } from '@/app/actions';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { Loader2, Sparkles } from 'lucide-react';

function SubmitButton() {
  const { pending } = useFormStatus();

  return (
    <Button type="submit" disabled={pending} size="lg" className="w-full text-lg font-bold group">
      {pending ? (
        <>
          <Loader2 className="mr-2 h-6 w-6 animate-spin" />
          Analyzing...
        </>
      ) : (
        <>
          Audit My Idea ($1.00)
          <Sparkles className="ml-2 h-5 w-5 group-hover:scale-125 transition-transform" />
        </>
      )}
    </Button>
  );
}

type LandingFormProps = {
  createCheckoutSession: (prevState: State, formData: FormData) => Promise<State>;
};

export default function LandingForm({ createCheckoutSession }: LandingFormProps) {
  const initialState: State = { message: '', error: '' };
  const [state, formAction] = useActionState(createCheckoutSession, initialState);
  const { toast } = useToast();

  useEffect(() => {
    if (state?.error) {
      toast({
        variant: 'destructive',
        title: 'An error occurred',
        description: state.error,
      });
    } else if (state?.fieldErrors?.idea) {
        toast({
            variant: 'destructive',
            title: 'Invalid Input',
            description: state.fieldErrors.idea.join(', '),
        });
    }
  }, [state, toast]);

  return (
    <form action={formAction} className="space-y-4">
      <Textarea
        name="idea"
        placeholder="e.g., I want to film a day in the life of a raccoon who secretly runs a tiny coffee shop."
        className="min-h-[120px] text-base p-4"
        required
      />
      <div className="space-y-2">
        <SubmitButton />
        <p className="text-xs text-muted-foreground px-2" style={{ textWrap: 'balance' }}>
          DISCLAIMER: The "Virality Score" and analysis are generated by an AI model based on current internet trends. This is a predictive tool for entertainment and creative guidance only. Receiving a high score does not guarantee actual viral performance, algorithm placement, or monetization on any social platform.
        </p>
      </div>
    </form>
  );
}
