import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <Link href="/" className="inline-flex items-center gap-2 text-muted-foreground hover:text-primary transition-colors mb-8">
          <ArrowLeft size={16} />
          Back to Home
        </Link>
        <h1 className="text-4xl font-bold text-primary mb-6">Terms of Service</h1>
        <div className="prose prose-invert max-w-none space-y-4 text-muted-foreground">
          <p>Last updated: {new Date().toLocaleDateString()}</p>
          <p>
            Please read these Terms of Service ("Terms", "Terms of Service")
            carefully before using the Trend Oracle website (the "Service")
            operated by us.
          </p>
          <h2 className="text-2xl font-semibold text-foreground pt-4">Service Description</h2>
          <p>
            Trend Oracle provides an AI-powered analysis of social media video
            ideas for entertainment and informational purposes. The analysis,
            including the virality score, critique, and hook script, is
            generated by an AI model and should not be considered a guarantee of
            actual performance or success.
          </p>
          <h2 className="text-2xl font-semibold text-foreground pt-4">Payments</h2>
          <p>
            A fee is required to use the Service. All payments are processed
            through our third-party payment processor, Stripe. By providing a
            payment method, you agree to their terms of service. All payments
            are non-refundable.
          </p>
          <h2 className="text-2xl font-semibold text-foreground pt-4">Intellectual Property</h2>
          <p>
            You retain all rights to the video ideas you submit. We claim no
            ownership over your content. The Service itself, including its
            look and feel, is the property of Trend Oracle.
          </p>
          <h2 className="text-2xl font-semibold text-foreground pt-4">Limitation of Liability</h2>
          <p>
            The Service is provided "as is." We make no warranties, expressed or
            implied, and hereby disclaim all other warranties. In no event shall
            Trend Oracle be liable for any damages (including, without
            limitation, damages for loss of data or profit, or due to business
            interruption) arising out of the use or inability to use the
            materials on Trend Oracle's website, even if Trend Oracle or a Trend
            Oracle authorized representative has been notified orally or in
            writing of the possibility of such damage.
          </p>
          <h2 className="text-2xl font-semibold text-foreground pt-4">Governing Law</h2>
          <p>
            These terms and conditions are governed by and construed in
            accordance with the laws of our jurisdiction and you irrevocably
            submit to the exclusive jurisdiction of the courts in that State or
            location.
          </p>
        </div>
      </div>
    </div>
  );
}
